name: coral-reef-classification
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - jupyterlab
  - ipykernel
  - tqdm
  - boto3
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - timm
      - transformers
      - huggingface_hub
      - safetensors

